/* The catalogue of cases. The details (episodes, clues, voices) live in each case's own file and
   register themselves into CASES. CASE_LIST is the small description the lobby and the phones show. */
const CASES = {};
const CASE_LIST = [
  { id: 'blackwood', title: 'The Blackwood Files', tag: 'Original', length: 'Four episodes · about 75 min', blurb: 'December, 1926. A blizzard seals Blackwood Manor, and its master is dead at his own dinner party. Five people are still under the roof. Search the rooms, catch the lies and vote on who did it.', hook: 'Every episode ends on a cliffhanger. Someone here is not who they seem. Perhaps more than one.', source: 'An original mystery' },
  { id: 'silverblaze', title: 'Silver Blaze', tag: 'Sherlock Holmes', length: 'Two episodes · about 40 min', blurb: 'The favourite for the Wessex Cup has vanished from its stable on Dartmoor, and its trainer lies dead on the moor with his head stove in. Holmes takes the night train. Who killed John Straker?', hook: 'The most important clue is something that did not happen.', source: 'After Arthur Conan Doyle, "Silver Blaze" (1892)' },
  { id: 'boscombe', title: 'The Boscombe Valley Mystery', tag: 'Sherlock Holmes', length: 'Two episodes · about 40 min', blurb: 'A farmer is found beaten to death beside a quiet pool. His own son is arrested, and nearly everyone is sure he did it. Holmes is not. Who killed Charles McCarthy?', hook: 'The dying man said two words. Everyone heard them. Only one person understood.', source: 'After Arthur Conan Doyle, "The Boscombe Valley Mystery" (1891)' },
  { id: 'abbey', title: 'The Abbey Grange', tag: 'Sherlock Holmes', length: 'Two episodes · about 40 min', blurb: 'A brutal baronet is killed in his own dining room, and his wife is found tied to a chair. She says burglars. Holmes counts the wine glasses. Who killed Sir Eustace Brackenstall, and what should be done about it?', hook: 'This time the jury is you.', source: 'After Arthur Conan Doyle, "The Adventure of the Abbey Grange" (1904)' }
];
